root = "."
  tmp_dir = "tmp"

  [build]
  cmd = "go build -o ./tmp/api.exe ./cmd/api"
  entrypoint = ["./tmp/api.exe"]

  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 500
  stop_on_error = true